//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SickId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string SicknessName { get; set; }
        public string MdicineName { get; set; }
        public string MdicineHowUse { get; set; }
        public string MdicineWhenUse { get; set; }
    
        public virtual Sick Sick { get; set; }
        public virtual User User { get; set; }
    }
}
